name: Webhook Trigger Workflow

on:
  push:

jobs:
  webhook-job:
    runs-on: ubuntu-latest

    steps:
      - name: Call Webhook
        id: call_webhook
        run: |
          response=$(curl -s -o response.txt -w "%{http_code}" -X POST "${{ secrets.WEBHOOK_URL }}")
          echo "Response code: $response"
          echo "response_code=$response" >> $GITHUB_ENV
          echo "response_body<<EOF" >> $GITHUB_OUTPUT
          cat response.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send Success Mail
        if: env.response_code == '200'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Webhook Success ✅"
          to: "recipient@example.com"
          from: "GitHub Actions <${{ secrets.MAIL_USERNAME }}>"
          body: |
            ✅ Webhook executed successfully on push!
            Response Code: ${{ env.response_code }}
            Response Body:
            ${{ steps.call_webhook.outputs.response_body }}

      - name: Send Failure Mail
        if: env.response_code != '200'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Webhook Failed ❌"
          to: "recipient@example.com"
          from: "GitHub Actions <${{ secrets.MAIL_USERNAME }}>"
          body: |
            ❌ Webhook execution failed.
            Response Code: ${{ env.response_code }}
            Response Body:
            ${{ steps.call_webhook.outputs.response_body }}
