name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # change branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Build
        run: echo "🚀 Running build steps here..."
        # replace with your actual build/test/deploy steps

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: always() # ensures this job always runs even if build fails

    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: ${{ needs.build.result == 'success' && '✅ Build Success' || '❌ Build Failed' }}
          to: yourmail@example.com
          from: GitHub Actions <${{ secrets.MAIL_USERNAME }}>
          body: |
            Hello,

            The GitHub Actions workflow for repository **${{ github.repository }}**
            and branch **${{ github.ref }}** has completed.

            Status: **${{ needs.build.result }}**

            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}

            Regards,
            GitHub Actions Bot
