name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"   # runs on every branch push

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Check webhook deliveries
        id: check
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WEBHOOK_PAT }}
          script: |
            const { owner, repo } = context.repo;
            const hook_id = process.env.WEBHOOK_ID;

            // Fetch last delivery
            const deliveries = await github.rest.repos.listWebhookDeliveries({
              owner,
              repo,
              hook_id,
              per_page: 1,
            });

            if (deliveries.data.length === 0) {
              core.setOutput("failed", "false");
              return;
            }

            const last = deliveries.data[0];
            console.log("Last delivery:", last);

            if (last.status === "timed_out") {
              console.log("Delivery timed out → retrying...");
              await github.rest.repos.redeliverWebhookDelivery({
                owner,
                repo,
                hook_id,
                delivery_id: last.id,
              });
              core.setOutput("failed", "true");
            } else if (last.status !== "ok") {
              core.setOutput("failed", "true");
            } else {
              core.setOutput("failed", "false");
            }
        env:
          WEBHOOK_ID: ${{ secrets.WEBHOOK_ID }}

      - name: Send failure email
        if: steps.check.outputs.failed == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "❌ Webhook Delivery Failed"
          to: ${{ secrets.ALERT_EMAIL }} # configure this secret with recipient email(s)
          from: GitHub Bot <bot@example.com>
          body: "The last webhook delivery timed out or failed. A redelivery was triggered."
