name: Webhook Monitor on Push

on:
  push:           # change this if you want pull_request, release, etc.
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest webhook delivery
        id: check
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WEBHOOK_PAT }}   # fine-grained PAT with repo + admin:repo_hook
          script: |
            const { owner, repo } = context.repo;
            const hook_id = process.env.WEBHOOK_ID; // store in repo secrets

            // Get last webhook delivery
            const deliveries = await github.rest.repos.listWebhookDeliveries({
              owner,
              repo,
              hook_id: hook_id,
              per_page: 1
            });

            const last = deliveries.data[0];
            console.log("Last delivery status:", last.status);

            if (last.status !== "SUCCESS") {
              console.log("Redelivering...");
              await github.rest.repos.redeliverWebhookDelivery({
                owner,
                repo,
                hook_id: hook_id,
                delivery_id: last.id,
              });
              core.setOutput("failed", "true");
            } else {
              core.setOutput("failed", "false");
            }

      - name: Send success email
        if: steps.check.outputs.failed == 'false'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "✅ Webhook Delivery Successful"
          to: you@example.com
          from: GitHub Bot <bot@example.com>
          body: "The webhook was delivered successfully."

      - name: Send failure email
        if: steps.check.outputs.failed == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "❌ Webhook Delivery Failed"
          to: you@example.com
          from: GitHub Bot <bot@example.com>
          body: "The webhook delivery failed. A redelivery attempt was triggered."
