name: Webhook Workflow

on:
  push:

jobs:
  webhook-job:
    runs-on: ubuntu-latest

    steps:
      - name: Send Webhook
        id: webhook
        run: |
          response=$(curl -s -o response.txt -w "%{http_code}" -X POST "https://your-webhook-url.com" \
            -H "Content-Type: application/json" \
            -d '{"event":"push"}')

          echo "Response code: $response"
          if [ "$response" -ne 200 ]; then
            echo "Webhook failed, retrying..."
            sleep 5
            retry=$(curl -s -o response_retry.txt -w "%{http_code}" -X POST "https://your-webhook-url.com" \
              -H "Content-Type: application/json" \
              -d '{"event":"push"}')

            echo "Retry Response: $retry"
            if [ "$retry" -ne 200 ]; then
              echo "status=failed" >> $GITHUB_OUTPUT
            else
              echo "status=success" >> $GITHUB_OUTPUT
            fi
          else
            echo "status=success" >> $GITHUB_OUTPUT
          fi

      - name: Send Success Mail
        if: steps.webhook.outputs.status == 'success'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "✅ Webhook Success"
          to: yourmail@example.com
          from: GitHub Actions <${{ secrets.GMAIL_USER }}>
          body: "Webhook delivered successfully after push."

      - name: Send Failure Mail
        if: steps.webhook.outputs.status == 'failed'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "❌ Webhook Failed"
          to: yourmail@example.com
          from: GitHub Actions <${{ secrets.GMAIL_USER }}>
          body: "Webhook delivery failed even after retry."
