name: Trigger Jenkins and Send Mail on Failure

on:
  push:
    branches:
      - main

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Webhook
        id: jenkins
        run: |
          RESPONSE=$(curl -s -o response.txt -w "%{http_code}" http://<NGROK_URL>/github-webhook/)
          echo "JENKINS_RESPONSE=$RESPONSE" >> $GITHUB_ENV
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Jenkins trigger failed with status $RESPONSE"
            cat response.txt || true
            exit 1
          fi

      - name: Send email if Jenkins trigger failed
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Jenkins Webhook Trigger Failed 🚨"
          to: "your-email@example.com"
          from: "GitHub Actions <your-email@example.com>"
          body: |
            The Jenkins webhook trigger has failed.

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}

            Failure Details:
            - HTTP Status: ${{ env.JENKINS_RESPONSE }}
            - GitHub Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
