name: CI Pipeline

on:
  workflow_dispatch:   # Manually trigger to test
  push:                # On push
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Build
        run: |
          echo "Simulating build..."
          exit 1   # <-- Force fail for testing (remove later)

      - name: Capture failure reason
        if: failure()
        run: |
          echo "Job failed at step: $GITHUB_JOB" >> failure_reason.txt
          echo "Error logs:" >> failure_reason.txt
          tail -n 50 $GITHUB_STEP_SUMMARY >> failure_reason.txt || echo "No detailed logs" >> failure_reason.txt

      - name: Send failure email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "❌ GitHub Workflow Failed: ${{ github.workflow }}"
          to: "yourmail@example.com"
          from: "GitHub Actions <${{ secrets.MAIL_USERNAME }}>"
          body: |
            Hi Team,

            The workflow **${{ github.workflow }}** has failed.
            
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref }}
            Commit: ${{ github.sha }}
            Actor: ${{ github.actor }}

            Failure Reason:
            -----------------
            ${{ job.status }}

            Please check GitHub Actions logs for more details.

            Regards,
            CI Bot
