name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a step that fails
        run: |
          echo "This step will fail to test email notification"
          exit 1   # Forces failure

      - name: Send Email on Failure
        if: failure()   # Runs only when any step fails
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "🚨 GitHub Actions Workflow Failed - ${{ github.repository }}"
          to: "yourmail@example.com"
          from: "GitHub Actions <${{ secrets.MAIL_USERNAME }}>"
          secure: true
          body: |
            Hello,

            The GitHub Actions workflow **${{ github.workflow }}** failed.
            
            Repository: **${{ github.repository }}**
            Branch: **${{ github.ref_name }}**
            Commit: **${{ github.sha }}**
            Triggered by: **${{ github.actor }}**

            Failure Reason: One of the pipeline steps exited with status code 1.
            
            Please check the logs here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Regards,  
            GitHub Actions Bot
