name: Monitor Webhooks

on:
  push:
    branches: [main]

jobs:
  check-webhook:
    runs-on: ubuntu-latest
    outputs:
      final_status: ${{ steps.check.outputs.final_status }}
    steps:
      - name: Check and Redeliver Webhook if Needed
        id: check
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WEBHOOK_PAT2 }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const hookId = 558736907;

            // Fetch latest delivery
            const { data: deliveries } = await github.request(
              "GET /repos/{owner}/{repo}/hooks/{hook_id}/deliveries",
              { owner, repo, hook_id: hookId }
            );

            const latest = deliveries[0];
            console.log("Latest delivery:", latest);

            let finalStatus = latest.status;

            // If not OK, retry delivery
            if (latest.status !== "ok") {
              console.log(`Webhook delivery ${latest.id} failed (${latest.status}). Retrying...`);
              await github.request(
                "POST /repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}/attempts",
                { owner, repo, hook_id: hookId, delivery_id: latest.id }
              );

              // Wait for GitHub to process redelivery
              await new Promise(r => setTimeout(r, 5000));

              // Get latest delivery again
              const { data: redeliveries } = await github.request(
                "GET /repos/{owner}/{repo}/hooks/{hook_id}/deliveries",
                { owner, repo, hook_id: hookId }
              );

              const newLatest = redeliveries[0];
              console.log("After redelivery:", newLatest);
              finalStatus = newLatest.status;
            }

            core.setOutput("final_status", finalStatus);

  send-email:
    needs: check-webhook
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "GitHub Webhook Status Notification"
          body: |
            Final Webhook Status: ${{ needs.check-webhook.outputs.final_status }}

            Repository: ${{ github.repository }}
            Commit SHA: ${{ github.sha }}
            Branch: ${{ github.ref }}

          to: photoskarthik2@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          secure: true
