name: Monitor Webhooks

on:
  push:
    branches: [main]

jobs:
  check-webhook:
    runs-on: ubuntu-latest
    outputs:
      webhook_status: ${{ steps.check.outputs.status }}
    steps:
      - name: Check webhook delivery
        id: check
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WEBHOOK_PAT2 }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const hookId = 558736907;

            const { data: deliveries } = await github.request(
              "GET /repos/{owner}/{repo}/hooks/{hook_id}/deliveries",
              { owner, repo, hook_id: hookId }
            );

            const latest = deliveries[0];
            console.log("Latest delivery:", latest);

            let status = latest.status;

            if (status !== "success") {
              console.log(`Webhook delivery ${latest.id} failed with status: ${status}. Retrying...`);
              await github.request(
                "POST /repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}/attempts",
                { owner, repo, hook_id: hookId, delivery_id: latest.id }
              );

              // Wait a few seconds before checking again
              await new Promise(resolve => setTimeout(resolve, 5000));

              const { data: updatedDeliveries } = await github.request(
                "GET /repos/{owner}/{repo}/hooks/{hook_id}/deliveries",
                { owner, repo, hook_id: hookId }
              );

              const redelivery = updatedDeliveries[0];
              console.log("Redelivery result:", redelivery);
              status = redelivery.status;
            }

            core.setOutput("status", status);
  send-email:
    needs: check-webhook
    if: needs.check-webhook.outputs.webhook_status != 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "GitHub Webhook Delivery Failed"
          body: |
            Webhook delivery failed.

            Status: ${{ needs.check-webhook.outputs.webhook_status }}
            Repo: ${{ github.repository }}
            Commit: ${{ github.sha }}
            Branch: ${{ github.ref }}

          to: photoskarthik2@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          secure: true
