name: Monitor Webhooks

on:
  push:
    branches: [main]

jobs:
  check-webhook:
    runs-on: ubuntu-latest

    steps:

      - name: Check webhook and redeliver if failed
        id: check-webhook
        env:
          GH_TOKEN: ${{ secrets.WEBHOOK_PAT2 }}
        run: |
          owner="${GITHUB_REPOSITORY%/*}"
          repo="${GITHUB_REPOSITORY#*/}"
          hookId=558736907

          echo "Checking latest webhook delivery for $owner/$repo (hook=$hookId)..."

          latest=$(gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/$owner/$repo/hooks/$hookId/deliveries | jq '.[0]')

          delivery_id=$(echo "$latest" | jq -r '.id')
          status=$(echo "$latest" | jq -r '.status')
          response_code=$(echo "$latest" | jq -r '.response.status_code')

          echo "Latest delivery: id=$delivery_id, status=$status, response=$response_code"

          if [[ "$status" == "OK" || "$response_code" == "200" ]]; then
            echo "✅ Webhook delivery $delivery_id succeeded (status=$status, response=$response_code)."
            echo "send_mail=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "Delivery $delivery_id failed (status=$status, response=$response_code). Retrying once..."

          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/$owner/$repo/hooks/$hookId/deliveries/$delivery_id/attempts

          echo "Waiting 10s before checking again..."
          sleep 10

          retried=$(gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/$owner/$repo/hooks/$hookId/deliveries | jq '.[0]')

          retry_id=$(echo "$retried" | jq -r '.id')
          retry_status=$(echo "$retried" | jq -r '.status')
          retry_response=$(echo "$retried" | jq -r '.response.status_code')

          echo "Retry delivery: id=$retry_id, status=$retry_status, response=$retry_response"

          if [[ "$retry_status" == "OK" || "$retry_response" == "200" ]]; then
            echo "✅ Webhook delivery $retry_id succeeded after retry (status=$retry_status, response=$retry_response)."
            echo "send_mail=false" >> $GITHUB_OUTPUT
          else
            echo "❌ Webhook delivery $retry_id failed after retry (status=$retry_status, response=$retry_response)."
            echo "mail_context=❌ Webhook delivery $retry_id failed after retry (status=$retry_status, response=$retry_response)." >> $GITHUB_OUTPUT
            echo "send_mail=true" >> $GITHUB_OUTPUT
          fi

      - name: Send mail
        if: steps.check-webhook.outputs.send_mail == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "GitHub Webhook Delivery Status"
          to: "photoskarthik2@gmail.com"
          from: "karthikknvamma@gmail.com"
          body: ${{ steps.check-webhook.outputs.mail_context }}
