name: Monitor Webhooks

on:
  push:
    branches: [main]

jobs:
  check-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Check webhook config
        id: check-webhook
        env:
          GH_TOKEN: ${{ secrets.WEBHOOK_PAT2 }}
        run: |
          owner="karthikbattula02"
          repo="RedShift_CICD"
          hookId=558736907

          echo "Checking webhook config for $owner/$repo (hook=$hookId)..."

          webhook=$(gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/$owner/$repo/hooks/$hookId)

          is_active=$(echo "$webhook" | jq -r '.active')
          hook_url=$(echo "$webhook" | jq -r '.config.url')

          echo "Webhook active: $is_active"
          echo "Webhook URL: $hook_url"

          if [[ "$is_active" != "true" ]]; then
            echo "❌ Webhook is inactive."
            echo "mail_context=❌ Webhook is inactive. URL: $hook_url" >> $GITHUB_OUTPUT
            echo "send_mail=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "Webhook is active. Proceeding to check last delivery status..."

      - name: Check latest delivery and redeliver if failed
        id: redeliver
        env:
          GH_TOKEN: ${{ secrets.WEBHOOK_PAT2 }}
        run: |
          owner="karthikbattula02"
          repo="RedShift_CICD"
          hookId=558736907

          latest=$(gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/$owner/$repo/hooks/$hookId/deliveries | jq '.[0]')

          delivery_id=$(echo "$latest" | jq -r '.id')
          status=$(echo "$latest" | jq -r '.status')
          response_code=$(echo "$latest" | jq -r '.response.status_code')

          echo "Latest delivery: id=$delivery_id, status=$status, response=$response_code"

          if [[ "$status" == "OK" || "$response_code" == "200" ]]; then
            echo "✅ Webhook delivery $delivery_id succeeded."
            echo "send_mail=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "❌ Delivery $delivery_id failed. Retrying..."

          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/$owner/$repo/hooks/$hookId/deliveries/$delivery_id/attempts

          echo "Waiting 10s before checking retry result..."
          sleep 10

          retried=$(gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/$owner/$repo/hooks/$hookId/deliveries | jq '.[0]')

          retry_id=$(echo "$retried" | jq -r '.id')
          retry_status=$(echo "$retried" | jq -r '.status')
          retry_response=$(echo "$retried" | jq -r '.response.status_code')

          echo "Retry delivery: id=$retry_id, status=$retry_status, response=$retry_response"

          if [[ "$retry_status" == "OK" || "$retry_response" == "200" ]]; then
            echo "✅ Retry succeeded."
            echo "send_mail=false" >> $GITHUB_OUTPUT
          else
            echo "❌ Retry failed."
            echo "mail_context=❌ Webhook delivery $retry_id failed after retry. Status=$retry_status, Response=$retry_response" >> $GITHUB_OUTPUT
            echo "send_mail=true" >> $GITHUB_OUTPUT
          fi

      - name: Send mail if needed
        if: steps.check-webhook.outputs.send_mail == 'true' || steps.redeliver.outputs.send_mail == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "GitHub Webhook Issue"
          to: "photoskarthik2@gmail.com"
          from: "karthikknvamma@gmail.com"
          body: ${{ steps.check-webhook.outputs.mail_context || steps.redeliver.outputs.mail_context }}
