name: Monitor Webhooks

on:
  push:
    branches: [main]

jobs:
  check-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Check webhook and redeliver if failed
        id: check-webhook
        env:
          GH_TOKEN: ${{ secrets.WEBHOOK_PAT3 }}
        run: |
          owner="karthikbattula02"
          repo="RedShift_CICD"
          hookId=558736907

          echo "Checking webhook config..."
          webhook=$(gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/$owner/$repo/hooks/$hookId)

          status=$(echo "$webhook" | jq -r '.last_response.status')
          response_code=$(echo "$webhook" | jq -r '.last_response.code')

          echo "Latest webhook response: status=$status, response_code=$response_code"

          if [[ "$status" == "ok" || "$response_code" == "200" ]]; then
            echo "✅ Webhook successful. No action needed."
            echo "send_mail=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "❌ Webhook failed. Fetching latest delivery ID to retry..."

          # Get the latest delivery ID
          latest_delivery=$(gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/$owner/$repo/hooks/$hookId/deliveries | jq '.[0]')

          delivery_id=$(echo "$latest_delivery" | jq -r '.id')

          echo "Retrying delivery ID: $delivery_id"

          # Attempt redelivery
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/$owner/$repo/hooks/$hookId/deliveries/$delivery_id/attempts

          echo "Waiting 10 seconds before checking retry result..."
          sleep 10

          # Recheck webhook response
          retried=$(gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/$owner/$repo/hooks/$hookId)

          retry_status=$(echo "$retried" | jq -r '.last_response.status')
          retry_response=$(echo "$retried" | jq -r '.last_response.code')

          echo "Retry result: status=$retry_status, response_code=$retry_response"

          if [[ "$retry_status" == "ok" || "$retry_response" == "200" ]]; then
            echo "✅ Webhook succeeded after retry."
            echo "send_mail=false" >> $GITHUB_OUTPUT
          else
            echo "❌ Webhook still failed after retry."
            echo "mail_context=❌ Webhook failed after retry (status=$retry_status, response=$retry_response)." >> $GITHUB_OUTPUT
            echo "send_mail=true" >> $GITHUB_OUTPUT
          fi

      - name: Send mail
        if: steps.check-webhook.outputs.send_mail == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "GitHub Webhook Delivery Status"
          to: "photoskarthik2@gmail.com"
          from: "karthikknvamma@gmail.com"
          body: ${{ steps.check-webhook.outputs.mail_context }}
