name: Monitor Webhooks

on:
  push:
    branches: [main]

jobs:
  check-webhook:
    runs-on: ubuntu-latest
    outputs:
      webhook_code: ${{ steps.check.outputs.code }}
    steps:
      - name: Check webhook delivery
        id: check
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WEBHOOK_PAT2 }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const hookId = 558736907;

            try {
              const { data: deliveries } = await github.request(
                "GET /repos/{owner}/{repo}/hooks/{hook_id}/deliveries",
                { owner, repo, hook_id: hookId }
              );

              const latest = deliveries[0];
              console.log("Latest delivery:", latest);

              let code = latest?.response?.code ?? 'no-response';

              if (code !== 200) {
                console.log(`Webhook delivery ${latest.id} returned code ${code}. Retrying...`);

                await github.request(
                  "POST /repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}/attempts",
                  { owner, repo, hook_id: hookId, delivery_id: latest.id }
                );

                // Wait a few seconds before checking again
                await new Promise(resolve => setTimeout(resolve, 5000));

                const { data: updatedDeliveries } = await github.request(
                  "GET /repos/{owner}/{repo}/hooks/{hook_id}/deliveries",
                  { owner, repo, hook_id: hookId }
                );

                const redelivery = updatedDeliveries[0];
                console.log("Redelivery result:", redelivery);

                code = redelivery?.response?.code ?? 'no-response';
              }

              core.setOutput("code", code);
            } catch (error) {
              console.log("Error checking webhook:", error.message);
              core.setOutput("code", "error");
            }

  send-email:
    needs: check-webhook
    if: needs.check-webhook.outputs.webhook_code != '200'
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "GitHub Webhook Delivery Failed"
          body: |
            Webhook delivery failed.

            HTTP Code: ${{ needs.check-webhook.outputs.webhook_code }}
            Repo: ${{ github.repository }}
            Commit: ${{ github.sha }}
            Branch: ${{ github.ref }}

          to: photoskarthik2@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          secure: true
